/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
    
/**
 *
 * @author FANNY
 */
public class Botones extends javax.swing.JFrame {
SimpleDateFormat dt = new SimpleDateFormat("dd-MM-yyyy");
String nombreTamano="";
String topping="";
String fecha=dt.format(new Date());
double sub=0.0;
String precio;
double subtop=0.0;
double iva=0.0;
double tot=0.0;

    /**
     * Creates new form Botones
     */
    public Botones() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngTamano = new javax.swing.ButtonGroup();
        jPanel7 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rbtnSencillo = new javax.swing.JRadioButton();
        rbtnDoble = new javax.swing.JRadioButton();
        rbtnJumbo = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        cbxChispas = new javax.swing.JCheckBox();
        cbxCajeta = new javax.swing.JCheckBox();
        cbxGomitas = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSubtotal = new javax.swing.JTextField();
        txtIva = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        btnSuma = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        btnEnviar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(600, 400));
        setSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setMinimumSize(new java.awt.Dimension(600, 400));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("HELADOS FANNY XD");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, -1, -1));

        jPanel7.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 30));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)), "TAMAÑO"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btngTamano.add(rbtnSencillo);
        rbtnSencillo.setText("Sencillo $20");
        jPanel1.add(rbtnSencillo, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 33, -1, -1));

        btngTamano.add(rbtnDoble);
        rbtnDoble.setText("Doble $30");
        rbtnDoble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnDobleActionPerformed(evt);
            }
        });
        jPanel1.add(rbtnDoble, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 74, -1, -1));

        btngTamano.add(rbtnJumbo);
        rbtnJumbo.setText("Jumbo $45");
        jPanel1.add(rbtnJumbo, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 115, -1, -1));

        jPanel7.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 170, 150));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 0)), "TOPPING"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbxChispas.setText("Chispas $5");
        jPanel3.add(cbxChispas, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 23, -1, -1));

        cbxCajeta.setText("Cajeta $10");
        jPanel3.add(cbxCajeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 49, -1, -1));

        cbxGomitas.setText("Gomitas $15");
        jPanel3.add(cbxGomitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 75, -1, -1));

        jPanel7.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 220, 150));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("SUBTOTAL");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 22, -1, -1));

        jLabel3.setText("IVA");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 60, -1, -1));

        jLabel4.setText("TOTAL");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 98, -1, -1));

        txtSubtotal.setEditable(false);
        jPanel4.add(txtSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 19, 114, -1));

        txtIva.setEditable(false);
        jPanel4.add(txtIva, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 57, 114, -1));

        txtTotal.setEditable(false);
        jPanel4.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 95, 114, -1));

        jPanel7.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 220, 160));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSuma.setText("SUMA");
        btnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaActionPerformed(evt);
            }
        });
        jPanel5.add(btnSuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 73, -1));

        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel5.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        btnCerrar.setText("CERRAR");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel5.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        btnEnviar.setText("ENVIAR");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        jPanel5.add(btnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, -1));

        jPanel7.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 230, 160));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel7.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 120, 50));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnDobleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnDobleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnDobleActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaActionPerformed
        // TODO add your handling code here:
        double subtotal=0.0;
        double total = 0.0;
        double ivaSub = 0.00;
        final double IVA = .16;
        double t1=0.0;
        if (rbtnSencillo.isSelected()) {
            subtotal = subtotal + 20;
            nombreTamano= "Sencillo";
            precio="20.0";
            sub=subtotal;
            
        }
        if (rbtnDoble.isSelected()) {
            subtotal = subtotal + 30;
            nombreTamano= "Doble";
            precio="30.0";
            sub=subtotal;
        }
        if (rbtnJumbo.isSelected()) {
            subtotal = subtotal + 45;
            nombreTamano="Jumbo";
            precio="45.0";
            sub=subtotal;
        }
        if (cbxChispas.isSelected()) {
            subtotal += 5;
            topping=topping + "Chispas"+"\n";
            sub=subtotal;
            subtop += 5;
        }
        if (cbxCajeta.isSelected()) {
            subtotal += 10;
            topping=topping + "Cajeta"+"\n";
            sub=subtotal;
            subtop += 10;
        }
        if (cbxGomitas.isSelected()) {
            subtotal += 15;
            topping=topping + "Gomitas";
            sub=subtotal;
            subtop += 15;
        }
               

        ivaSub = subtotal * IVA;
        DecimalFormat df = new DecimalFormat("#.00");
        t1=subtotal-ivaSub;
        total = t1 + ivaSub;
        txtSubtotal.setText(Double.toString(subtotal));
        txtIva.setText((df.format(ivaSub)));
        txtTotal.setText(Double.toString(total));
        iva=ivaSub;
        tot=total;
        
        
 /* JOptionPane.showMessageDialog(null,
    dt.format(dcFecha.getDate()),
    "Mensaje",
    JOptionPane.INFORMATION_MESSAGE);
     */

    }//GEN-LAST:event_btnSumaActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        // TODO add your handling code here:
        Ticket t = new Ticket();
        t.setTamano(nombreTamano);
        t.setFecha(fecha);
        t.setTopping(topping);
        t.setSubtotal(sub);
        t.setPrecio(precio);
        t.setPretop(subtop);
        t.setIva(iva);
        t.setTot(tot);
        t.setVisible(true);
        
        
        
        
        
        
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        txtIva.setText(null);
        txtSubtotal.setText(null);
        txtTotal.setText(null);
        btngTamano.clearSelection();
        if(cbxCajeta.isSelected()){
            cbxCajeta.setSelected(false);
        }
        if(cbxChispas.isSelected()){
            cbxChispas.setSelected(false);
        }
        if(cbxGomitas.isSelected()){
        cbxGomitas.setSelected(false);
        }
            
        
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Botones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Botones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Botones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Botones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Botones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSuma;
    private javax.swing.ButtonGroup btngTamano;
    private javax.swing.JCheckBox cbxCajeta;
    private javax.swing.JCheckBox cbxChispas;
    private javax.swing.JCheckBox cbxGomitas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton rbtnDoble;
    private javax.swing.JRadioButton rbtnJumbo;
    private javax.swing.JRadioButton rbtnSencillo;
    private javax.swing.JTextField txtIva;
    private javax.swing.JTextField txtSubtotal;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
