/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author FANNY
 */
public class Principal extends javax.swing.JFrame {
    // String ruta = "";

    URL url = null;
    ImageIcon icon = null;

    public Principal() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblOpcion = new javax.swing.JLabel();
        jcbOpciones = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstListado = new javax.swing.JList<>();
        btnLista = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblOpcion.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lblOpcion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOpcion.setText("SELECCIONE  UNA  OPCION");
        lblOpcion.setToolTipText("");
        lblOpcion.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblOpcion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblOpcion.setMaximumSize(new java.awt.Dimension(128, 128));
        lblOpcion.setMinimumSize(new java.awt.Dimension(128, 128));
        lblOpcion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(lblOpcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 190, 190));

        jcbOpciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jcbOpciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbOpcionesActionPerformed(evt);
            }
        });
        jPanel2.add(jcbOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, -1, -1));

        lstListado.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Opción 1", "Opción 2", "Opción 3" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstListado);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 110, 110));

        btnLista.setText("OPCION");
        btnLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaActionPerformed(evt);
            }
        });
        jPanel2.add(btnLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 727, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbOpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbOpcionesActionPerformed
        // TODO add your handling code here:
        int op = jcbOpciones.getSelectedIndex();
        String cadena = jcbOpciones.getSelectedItem().toString();

        switch (op) {
            case 0:
                this.mostrarImagen("/imagenes/Dancing.png", op + 1, cadena);
                JOptionPane.showMessageDialog(null, "Opción 1",
                        "Opcion Seleccionada", JOptionPane.INFORMATION_MESSAGE);
                /* ruta = "/imagenes/Dancing.png";
                url = this.getClass().getResource(ruta);
                icon = new ImageIcon(url);
                lblOpcion.setText(null);
                lblOpcion.setIcon(icon);
                 */
                break;
            case 1:
                this.mostrarImagen("/imagenes/Happy.png", op + 1, cadena);
                JOptionPane.showMessageDialog(null, "Opción 2",
                        "Opcion Seleccionada", JOptionPane.INFORMATION_MESSAGE);
                /*  ruta = "/imagenes/Dancing.png";
                url = this.getClass().getResource(ruta);
                icon = new ImageIcon(url);
                lblOpcion.setText(null);
                lblOpcion.setIcon(icon); */
                break;
            case 2:
                this.mostrarImagen("/imagenes/Minion.png", op + 1, cadena);
                JOptionPane.showMessageDialog(null, "Opción 3",
                        "Opcion Seleccionada", JOptionPane.INFORMATION_MESSAGE);
                /* ruta = "/imagenes/Dancing.png";
                url = this.getClass().getResource(ruta);
                icon = new ImageIcon(url);
                lblOpcion.setText(null);
                lblOpcion.setIcon(icon); */
                break;
            default:
                throw new AssertionError();
        }
    }//GEN-LAST:event_jcbOpcionesActionPerformed
    public void mostrarImagen(String urlImagen, int opcion, String cad) {
        // ruta = urlImagen;
        url = this.getClass().getResource(urlImagen);
        icon = new ImageIcon(url);
        //lblOpcion.setText(null);
        lblOpcion.setIcon(icon);
        lblOpcion.setText("SELECCIONASTE LA OPCIÓN " + opcion);
        //lblOpcion.setText("Opcion: "+ opcion + "Texto:" + cad);

    }

    private void btnListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaActionPerformed
        // TODO add your handling code here:
        int opc = lstListado.getSelectedIndex();

        /* JOptionPane.showMessageDialog(null, "Opcion No " + opc,
                "Opcion seleccionada",
                JOptionPane.INFORMATION_MESSAGE); */
        switch (opc) {
            case -1:
                /* JOptionPane.showMessageDialog(null, "Selecciona una opción",
                        "ERROR", JOptionPane.ERROR_MESSAGE); */
                JOptionPane.showMessageDialog(null, "Selecciona una opción",
                        "ERROR", JOptionPane.WARNING_MESSAGE);
                break;
            case 0:
                mostrarCuadro(opc + 1);
                break;
            case 1:
                mostrarCuadro(opc + 1);
                break;
            case 2:
                mostrarCuadro(opc + 1);
                break;
        }
    }//GEN-LAST:event_btnListaActionPerformed
    public void mostrarCuadro(int op) {
        JOptionPane.showMessageDialog(null, "Opción No: " + op, "Opción seleccionada",
                JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLista;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbOpciones;
    private javax.swing.JLabel lblOpcion;
    private javax.swing.JList<String> lstListado;
    // End of variables declaration//GEN-END:variables
}
